### ISSUE TITLE
Missing flag to avoid decryption in tests

### ISSUE THREAD

**Issue by AnnaSkawinska** [ulisesbocchio/jasypt-spring-boot#104]
Is it possible to tur off decryption of properties in integration tests?

I've got a bunch of `@SpringBootTest`s which raise Spring context including property source beans, so in case I don't provide `jasypt.encryptor.password`, context creation fails.

I don't necessarily want to take care of storing the password a safe way for tests only. In my tests I don't also need the properties to be decrypted. Is there a way of turning off the decryption process?

If not - a property like `jasypt.encryptor.enabled` would come in very handy.

**Comment by ulisesbocchio** [comment]
It should not bother you if you don’t have any encrypted properties. But I’ll doble check

**Comment by melloware** [comment]
I am using 2.1.0 and I am seeing behavior I didn't expect.

ENC property like this works fine
`spring.datasource.password=ENC(1W+NaD8JG7UvJE/7tc8iQg==)`

if I use the clear text version it is still trying to decrypt it for some reason.  Is it looking for properties that contain the word "password" instead of just properties that use ENC()?
`spring.datasource.password=clear`

**Comment by ulisesbocchio** [comment]
Ok, do you have another ENC() property somewhere else? I just tested one of the sample apps and as far as I don't have any ENC() decorated property I don't need to set the password.
Check this sample where app and tests don't provide password and everything runs properly: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo-no-password
