### ISSUE TITLE
Placeholder replacement in xml context files does not work

### ISSUE THREAD

**Issue by mmrath** [ulisesbocchio/jasypt-spring-boot#13]
Not sure if it is allowed to work. but this config does not work
```xml
<bean id="simpleBean" class="com.example.SimpleBean">
    <property name="value" value="${my.simple.value}" />
</bean>
```

I see the value property is not decrypted.

**Comment by ulisesbocchio** [comment]
Can you provide a little more context? I'm not sure what you're trying to do and how you're configuring your Spring Boot application. Do you have a sample project on Github where you have this issue?

**Comment by mmrath** [comment]
@ulisesbocchio I have uploaded a sample test repo at https://github.com/mmrath/jasypt-sb-test

When you run the example it prints 
Simple bean valueENC(PBnDZTzdWSIhTDcM9+vcHmeUQjVBvTyJ)

instead of 
Simple bean valuepassword

**Comment by ulisesbocchio** [comment]
Alright buddy you can use Spring EL this way to inject the property in your bean:
```
    <bean id="simpleBean" class="demo.SimpleBean">
        <property name="value" value="#{environment['my.simple.value']}" />
    </bean>
```
Regardless of this, I found the problem after some debugging of Spring code. It turns out my Ordered post processor that decorates property sources needed to implement PriorityOrdered instead, and be of HIGHEST precedence to be able to decorate the property sources before the PropertySourcesPlaceHolderConfigurer kicks in when reading config from XML. 
Version 1.4 should be in Maven Central soon

**Comment by mmrath** [comment]
Thanks @ulisesbocchio . I guessed something to do with the post processor. I had the work around  of using SPEL.
