### ISSUE TITLE
Melloware Jasypt uses a very old snapshot of Jasypt

### ISSUE THREAD

**Issue by joshua-baton** [ulisesbocchio/jasypt-spring-boot#145]
As far as I can tell the melloware version of Jasypt, which this codebase is now using, is a 3 year old copy of the jasypt codebase from the sourceforge SVN server.  If I am wrong here please correct me.  If I am correct, could someone please explain the logic behind building higher level encryption support on top of this instead of on top the official jasypt guthub repo?  My project uses this library for database and property encryption and switching to an old snapshot of jasypt is concerning me.  Thanks.

**Comment by melloware** [comment]
@joshua-baton Jasypt did not do a release in 5 years (since late 2013).  Jasypt 1.9.2 did not support JDK8 or any of the higher level of encryption like PBEWITHHMACSHA512ANDAES_256.  So we forked it and made the fixes allowing it to work with JDK8 and the new higher encryption levels.

Multiple attempts to contact the Jasypt authors over the years were getting no response in fact to the point there was speculation they had passed away.    So about 3 months after I made my fork and fixed this project they magically reappeared and made a Jasypt 1.9.3 release.

You can see the whole thread here: https://sourceforge.net/p/jasypt/bugs/32/ . Bug created in 2014 no answers from the original authors until a few months ago!

This PR https://github.com/ulisesbocchio/jasypt-spring-boot/pull/151 will fix it by updating to Jasypt 1.9.3.
