### ISSUE TITLE
Request: Maven flag - Do not change the value special flag for maven plug-in build

### ISSUE THREAD

**Issue by Adriansun** [ulisesbocchio/jasypt-spring-boot#181]
Request: Maven flag - Do not change the value special flag for maven plug-in build

The Maven plug-in is good. Thank you for that. I have a request. An additional flag would be great. As of now the maven plug-in and work flow seems to work like this:

1. Set one or several lines in application.properties to whatever=DEC(superSecret).
2. Run "mvn clean install jasypt:encrypt -Djasypt.encryptor.password="the password"".
3. The plug-in changes the "whatever" value to ENC(someencryptedletters) in the project.
4. It builds the war file with ENC(someencryptedletters) as value for "whatever".

Point 3 and 4 above are the ones I have an issue with. This is what I would like the jasypt maven plug-in to do:

1. Set one or several lines in application.properties to whatever=DEC(superSecret).
2. Run "mvn clean install jasypt:encrypt -Djasypt.encryptor.password="the password" -flagLetItBeTheSameInTheProjectFileButEncrytpItInTheBuildFile".
3. The plug-in does not change the "whatever" value, but instead lets it stay as it is in the project.
4. (But) It builds the war file with ENC(someencryptedletters) as value for "whatever". 

The "whatever" line's value is now encrypted in the war/jar file; the IT-guy or hacker will not be able to see the real password if they would get hold of the war/jar file and open it. The reason for this is that I am working alone on a project. The fact that I can see the password(s) or that the password(s) is on my internal gitlab does not matter. The problem is if other people can see it when I give the war/jar away. I would like jasypt to encrypt the line when Maven is building the war/jar file(s), but not change the value in the property file that I visually can see, since I might need to change / check password(s)/username(s) and such from time to time during development, and also check things after a version has been passed as a valid build to be put into production since the development will always continue. Right now, if I want to use the maven plug-in, I guess I have to first copy the properties files with the un-encrypted values, run "mvn clean install jasypt:encrypt -Djasypt.encryptor.password="the password"", and then finally copy-paste back in the un-encrypted values so I can continue to work. Would it be possible to create a flag as I suggested? Is it possible already? If it is possible could the manual be updated to show how or what is needed to make it as I wish, please?

**Comment by ulisesbocchio** [comment]
the idea is that you never store a file with unencrypted secrets, no matter where you have it.
Ideally you store the actual secret in a secret manager and then you always keep the value encrypted in your properties

**Comment by Adriansun** [comment]
Okay. I hear you. But two questions araise:
1. What secret manager do you recommend?
2. What is the point with the new maven plug-in of "ENC(..." if we are not to store the secrets there ever?

**Comment by ulisesbocchio** [comment]
Sorry, I was probably too vague on my explanation. 
On point 2 of your last comment, you're right. We're storing the secret in the config file (encrypted). What I meant is that we shouldn't store the secrets in clear form in the config file. 
In your original issue you were mentioning that you would like the plugin to take your "whatever" value and encrypt it in the WAR but leave it clear text in your project, that's the part IMO is not a good thing because anybody with access to your project would know the password.
That's the implicit reason why the plugin encrypts in place, because you want that property to be store in your config file in your repo encrypted at rest so no one can make sense of it, even if they have access to the repo.
The secret management part is where your system administrator keeps the real decryption password safely stored to configure your application environments. It could be a text file, a kubernetes secret, vault, etc.

**Comment by Adriansun** [comment]
Hello again,

2) You are correct about what I would like to have. I still do not see why you would not honor my wish. If we continue on your path; then where should I put my secrets and be able to _only change them in one place_ (if needed), and by doing that, propagate that change throughout the whole chain to the compiling/build stage? Tutorial, please? There are many sub-systems in projects which makes thing complicated. What I want is to simplify. It would be preferable to be able to see the secrets without having to inserting them over and over again (if they need to change), which we have to do now. Like I said: I will be the only one seeing the secrets as a developer of a small business. I / we few may see the / some secrets then that is no problem. The only problem is when the built files are "given away" to others. What is even the point of this maven build plug-in if the secrects do not stay as they are (un-encrypted) for us developers? I can see a benefit or two, but not all of them by using the maven plug-in.

**Comment by rupert-madden-abbott** [comment]
@Adriansun 

The reason the plugin changes the files in place is because it isn't really intended that you would run this plugin as part of a build. Instead the process is more like this:

1. Write some code and add a decrypted property
2. Run jasypt:encrypt and encrypt the property
3. Check your code into version control
4. Push your code up to a version control server
5. Continuous Integration/Deployment server builds your code from version control including already encrypted properties


The point is that your sensitive properties are not stored in plaintext in version control.


"The only problem is when the built files are "given away" to others"

What do you mean by given away to others? Don't forget that if you are giving somebody the built jar, and also given them the encryption key, then it is no safer than just having the password in plaintext.

If you want to check what the decrypted values are, you can just run jasypt:decrypt.
If you want to change a decrypted value, just replace the encrypted value with DEC(YOUR_NEW_VALUE) and run jasypt:encrypt.
