### ISSUE TITLE
encrypted spring properties inside logback-spring.xml file

### ISSUE THREAD

**Issue by kbjp2** [ulisesbocchio/jasypt-spring-boot#24]
Hi,
I'm using spring properties (from application.yml file) inside my logback-spring.xml (see logback extensions inside the spring-boot doco)
That works fine but *not* for encrypted properties (I would like to make use of a DBAppender with an encrypted password coming from the spring config file).
Would you have any suggestion on how to make it work ?
Regards
kbjp

**Comment by ulisesbocchio** [comment]
Let me take a look and I'll get back to you.
Thanks,
Uli

**Comment by ulisesbocchio** [comment]
I believe this is what you're looking for: https://github.com/spring-projects/spring-boot/commit/055ace37f006120b0006956b03c7f358d5f3729f

Basically, Spring added Logback support for doing this in your logback configuration:

```
<configuration>
		...
		<springProperty name="destination" source="my.loggger.extradest"/>
		<appender name="FILE" class="ch.qos.logback.core.FileAppender">
			<file>${destination}</file>
				...
			</file>
		</appender>
		...
	</configuration>
```

**Comment by kbjp2** [comment]
Hi Ulises,
Thank you very much for coming back to me.
The setting that you mentionned above is indeed what I'm using in my logback file.
The problem is that the encrypted spring properties don't seem to be decrypted on-the-fly (in my personal case, I just have jasypt-spring-boot jar as a maven dependency, a "@SpringBootApplication" annotation and an application.yml resource file with encrypted properties).
Does on-the-fly property-decryption work for you inside a logback-spring config file ?
Thank you  very much in advance for your expertise.
Best Regards

**Comment by ulisesbocchio** [comment]
Hmm... That's interesting, I was betting on it working, but let me do some debugging with logback configuration. I haven't really tried your scenario. Do you happen to have some sort of demo app where the issue manifest that I can checkout from GitHub?
Best,
Uli

**Comment by kbjp2** [comment]
In order to reproduce the issue, you can use for example Spring demo project " Serving Web Content with Spring MVC" under https://spring.io/guides then the 3 following steps:

1) add jasypt-spring-boot-starter jar to your dependencies

2) add a "application.yml" file like:
jasypt.encryptor.password: your_encryption_key_here
encryptedproperty: ENC(your_encrypted_value_here)

3) a logback-spring.xml like: 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <springProperty scope="context" name="encryptedproperty" source="encryptedproperty"/>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%property{encryptedproperty} %msg%n</pattern>
    </encoder>
  </appender>
  <root level="info">
    <appender-ref ref="STDOUT" />
  </root>
</configuration>

**Comment by ulisesbocchio** [comment]
You'll have to use another type of setup. Spring is loading Logging configuration very early on the bootstrap process, way before this plugin decorates properties using a bean post processor. I just released a new version of the plugin (1.7) that will allow you to define a custom Environment in your application this way:

```java
new SpringApplicationBuilder()
                .environment(new EncryptableEnvironment(new StandardServletEnvironment()))
                .sources(YourApplicationClass.class).run(args);
```
The new environment basically decorates the StandardServletEnvironment, or any other ConfigurableEnvironment implementation. With this setup, you do not need to use the starter jar, just jasypt-string-boot, but it has it's limitations. For configuration, You'd have to pass the encryption password as a system property and any other configuration for the StringEncryptor that's available as a property. Or, you can populate the properties in the decorated environment, by either directly adding a property source to the decorated environment, or by setting the properties in the SpringApplicationBuilder.
Otherwise, if you want to provide your own StringEncryptor, you could use the other constructor:

```java
StringEncryptor encryptor = ...;
new SpringApplicationBuilder()
                .environment(new EncryptableEnvironment(new StandardServletEnvironment(), encryptor))
                .sources(YourApplicationClass.class).run(args);
```
But it'd be up to you how you initialize the string encryptor.

**Comment by kbjp2** [comment]
Perfect ! :-) 
Thanks a lot for your expertise and your time, Ulises !

**Comment by ulisesbocchio** [comment]
No worries, thanks for using the library!

**Comment by kbjp2** [comment]
In case you find time to answer: 
how long will it take for the new binaries to be available (and visible) in maven central ?

**Comment by kbjp2** [comment]
I can see it now in Maven central ! :-)
