### ISSUE TITLE
Cannot decrypt from env variable

### ISSUE THREAD

**Issue by niconatalie** [ulisesbocchio/jasypt-spring-boot#27]
Hello,

Can I use it to decrpyt value from Environment Variable?

I tried something like this:
spring.datasource.password=ENC(${DB_PASSWORD})

and I got an error : org.jasypt.exceptions.EncryptionOperationNotPossibleException: null

Thank you.

**Comment by ulisesbocchio** [comment]
you could. Any property from any property source could be encrypted. I think you're passing the property the wrong way. you gotta do:
```
spring.datasource.password=${DB_PASSWORD}
```
And DB_PASSWORD should contain the "ENC()".
Another thing you could do is to just use SPRING_DATASOURCE_PASSWORD as your environment variable since Spring Boot will convert _ to . automatically.

**Comment by niconatalie** [comment]
Thank you so much, I have wrapped my value in the environment with ENC() and it's work as charm.

And for SPRING_DATASOURCE_PASSWORD, I'm running multiple spring application on my development machine, with different credential on each apps.
