### ISSUE TITLE
loading encrypted password from database

### ISSUE THREAD

**Issue by pvpkiran** [ulisesbocchio/jasypt-spring-boot#31]
Hi,
  In my spring boot application, I am loading some passwords(password of remote machines for doing scp) from database on startup. So in database if I store ENC(encryptedpassword), this is not getting decrypted when it is loaded. But if I store the same thing in my properties file and load it, it is properly decrypted. 
Is it possible to store in database encrypted password like ENC(encryptedpassword) and get the encrypted password decrypted automatically when I load my application. 

As an alternative now I am doing this 
I store the encryptedpassword in DB(without **ENC()**) And in my application, before I use this password I do 
```
 BasicTextEncryptor textDecryptor = new BasicTextEncryptor();
 textDecryptor.setPassword(encryptDecryptKey);
 textDecryptor.decrypt(encryptedpasswordfromDb)
```

Thanks
Panikiran

**Comment by ulisesbocchio** [comment]
For this library to work with any properties they need to be in the form of a `PropertySource`, so you can create a new `PropertySource` with your DB  values and that should work. Provided that you register the `PropertySource` early on so that `jasypt-spring-boot` decorators can decorate your property source. Otherwise you'd have to wrap it yourself in an `EncryptablePropertySource` such as `EncryptableMapPropertySourceWrapper` to wrap properties of a `MapPropertySource`.
Something like this should do the trick:

```java
public static void main(String[] args) {
        new SpringApplicationBuilder()
            .sources(SecurityDemoApplication.class)
            .initializers(new ApplicationContextInitializer<ConfigurableApplicationContext>() {
                @Override
                @SneakyThrows
                public void initialize(ConfigurableApplicationContext applicationContext) {
                    DataSource dataSource = applicationContext.getBean(DataSource.class);
                    ResultSet propertiesResult = dataSource.getConnection().prepareStatement("select key, value from config_properties").executeQuery();
                    Map<String, Object> dbPropertiesMap = new HashMap<>();
                    while (propertiesResult.next()) {
                        dbPropertiesMap.put(propertiesResult.getString(1), propertiesResult.getString(2));
                    }
                    PropertySource<?> dbProperties = new MapPropertySource("dbProperties", dbPropertiesMap);
                    applicationContext.getEnvironment().getPropertySources()
                        .addLast(dbProperties);
                }
            })
            .run(args);
    }
```

Assuming that there is a `DataSource` bean in your application context. You'd have to tweak the query to fit your database.
