### ISSUE TITLE
@EnableEncryptableProperties are breaking rabbitmq initialization using Spring Data Flow

### ISSUE THREAD

**Issue by ravindrarjpt9** [ulisesbocchio/jasypt-spring-boot#328]
Spring data flow is not working with **jasypt-spring-boot** while annotating @EnableEncryptableProperties , it' looking breaking rabbitmq initialization. if i comment the annotation (EnableEncryptableProperties) , RabbitMQ initialized but it will break the encrypted properties (they will no more be decrypted). do we have any work around to support  rabbitmq initialization and encryption/decryption at same time.

**Comment by Akhil1991** [comment]
But @ulisesbocchio @rockyhopper  any insights why was the bean written using functional programming 

@Bean(name = CONFIG_SINGLETON)
    public Singleton<JasyptEncryptorConfigurationProperties> configProps(
            final EnvCopy envCopy) {
        return new Singleton<>(() -> JasyptEncryptorConfigurationProperties.bindConfigProps(envCopy.get()));
    }

because from spring boot 3, the spring cloud stream considers  functional programming as a stream event hence takes this one as a streaming event and produces events, can we not use functional programming because it requires additional step of adding function definition, and stream properties 

https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html

https://spring.io/projects/spring-cloud-function

Upgrading to springboot 3 , can’t use any more old  jasypt or anywork without much configuration  changes
