### ISSUE TITLE
Spring Boot warning for com.ulisesbocchio.jasyptspringboot.configuration.EncryptablePropertyResolverConfiguration

### ISSUE THREAD

**Issue by NishantHadole** [ulisesbocchio/jasypt-spring-boot#44]
Spring Boot version: 1.5.1.RELEASE
jasypt-spring-boot-starter version: 1.11

We see this warning every-time we run the application, although it does not affect the functionality. May be you can investigate the cause and fix it.

### **`WARN  o.s.c.a.ConfigurationClassPostProcessor - Cannot enhance @Configuration bean definition 'beanNamePlaceholderRegistryPostProcessor' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.`**

**Comment by ulisesbocchio** [comment]
It's been around for a while. If you look at `EncryptablePropertyResolverConfiguration.beanNamePlaceholderRegistryPostProcessor` it is a `static` `@Bean` declaration, so it seems like the warning is incorrectly logged. The warning states that be bean definition should be `static` and in fact it is since it needs to be static because it's a `BeanDefinitionRegistryPostProcessor` that needs to be picked up as early as possible in the bootstrap process.
You can turn off the warning by adding this to your configuration:

```yaml
logging.level:
  org.springframework.context.annotation.ConfigurationClassPostProcessor: off
```

**Comment by NishantHadole** [comment]
@ulisesbocchio 
Thanks for clarification.
