### ISSUE TITLE
@ConditionalOnProperty fails with @EncryptablePropertySource

### ISSUE THREAD

**Issue by kenkc** [ulisesbocchio/jasypt-spring-boot#49]
It looks like there is an issue with using @ConditionalOnProperty in conjunction with @EncryptablePropertySource. I have a bean which is annotated with 
@ConditionalOnProperty(name = "bean.enabled", matchIfMissing = false)
and I am importing the properties with 
@EncryptablePropertySource(value = { "classpath:beans.properties" })
and beans.properties contains the property "bean.enabled=true"
The bean is not instantiated. Commenting out the @ConditionalOnProperty annotation allows the bean to be created, and all other properties are loaded correctly.

**Comment by ulisesbocchio** [comment]
Interesting issue, let me dig on that...

**Comment by ulisesbocchio** [comment]
Alright so you can do this:
```java
@PropertySource(name = "EncryptedProperties", value = "classpath:encrypted.properties")
@EnableEncryptableProperties
```
And that will effectively encrypt the property source imported with the `@PropertySource` annotation. The downside is that if you `@ConditionalOnProperty`'s `havingValue` property you can't use a decrypted value. In other words, you can use this as far as you don't use an encrypted property with `havingValue`. So you can use any other property, or you can check for just the existence of an encrypted property.
The reason this doesn't work is because the property sources are picked up really early in the game before bean definitions, and that is not the case of property sources created with `@EncryptablePropertySource` since they're created with a `BeanDefinitionRegistryPostProcessor` and that's the earliest in the game I have found to integrate the annotation.

If you need to use `havingValue` from `@ConditionalOnProperty` depending on the value of an encrypted property, then your only option is to use:

```java
new SpringApplicationBuilder()
                .environment(new EncryptableEnvironment(new StandardEnvironment()))
```
on your spring application builder, but again, for bean conditionals on properties you're limited to either the `EncryptableEnvironment` or `EnableEncryptableProperties`
