### ISSUE TITLE
Suggestion: Merge with Jasypt Project

### ISSUE THREAD

**Issue by jlchoike** [ulisesbocchio/jasypt-spring-boot#55]
Hello!

I reached out to Chus Picos from the Jasypt project to ask if they had plans to officially support Spring Boot integration. Has anyone from that project reached out to you in the past or recently? 

Jan Choike

**Comment by ulisesbocchio** [comment]
Hi Jan, nobody ever contacted me from the Jasypt project. They've been quiet for quite a while.

**Comment by jlchoike** [comment]
Please e-mail me at jan.choike@gm.com. I would like to discuss other details and intentions for my inquiry. Thanks!

**Comment by ulisesbocchio** [comment]
@jlchoike can we discuss here?

**Comment by jlchoike** [comment]
Sure!

A few weeks ago, I reached out to the Jasypt team, because their library is approved open source at my company. Currently, yours is under consideration, but is viewed as a potential risk since the project is maintained primarily by you. A person with decision authority in my organization asked if the Jasypt project maintainers have thought of adding support for Spring Boot; and Chus Picos, from the Jasypt project, mentioned that they would consider adding Spring Boot support. At this point, we are trying to evaluate the risk of adding your library as approved open source by investigating the relationship between your project and the Jasypt project. Our ultimate goal is to identify a library that supports integration of Jasypt with Spring Boot - how that happens is what I hope our conversation will lead to.
 
Looking forward to your feedback. Thanks for help!

**Comment by ulisesbocchio** [comment]
I see, while I would definitely advise to use the library, to be honest with you, adding Jasypt to spring boot is no big deal. There are a variety of approaches that could be followed but the two closest to regular spring that you can use (if jasypt-spring-boot is not approved) are:
* the big ole `PropertyPlaceHolderConfigurer` for which jasypt actually provides a class for: [`EncryptablePropertyPlaceholderConfigurer`](http://www.jasypt.org/spring3.html). And it's still current even for the upcoming Spring 5
* The more modern Environment (since spring 3.1) and the `PropertySource` class for which there are plenty of examples out there on how to add your own property source. Jasypt also has it's own section on its [website](http://www.jasypt.org/spring31.html#Encryptable_PropertySource_implementation_for_Spring_3.1), which adapted to spring boot would be something like this:
```java
@SpringBootApplication
public class MyBootApp {
    public static void main(String[] args) {
        EncryptablePropertiesPropertySource encPropSource =
            new EncryptablePropertiesPropertySource("encProps", properties, encryptor);
  ApplicationContext ctx = new SpringApplicationBuilder()
                .sources(SimpleStarterDemoApplication.class).run(args);
  MutablePropertySources sources = ctx.getEnvironment().getPropertySources();
  sources.addFirst(encPropSource);
        
    }
}
```
And that's just the touch point between jasypt and spring, you also need to actually read the `properties` and configure the `encryptor`.

**Comment by jlchoike** [comment]
Thanks for the info and suggestion. Actually, we started using your library after finding that implementing comparable behavior would be no different than what you have already implemented. If there are any concerns for support, the decision to continue using your library will be a matter either reporting issues to you versus implementing our own solution similar to what you described.

**Comment by ulisesbocchio** [comment]
sounds good :), closing this
