### ISSUE TITLE
[Question] How to use ENC placeholder as sub-string in property value

### ISSUE THREAD

**Issue by ajainy** [ulisesbocchio/jasypt-spring-boot#57]
Use case: 

secret.password=ENC(sdfsdfds...)
secret.url=http://user:${secret.password}@domain.com 

Now secret URL when accessed, looks like it is NOT decrypting. 
But when i tested `secret.url` by inject property in java bean, it shows right values. 

I am trying to build `spring.cloud.config.uri` in spring boot config client app, without exposing actual password.

**Comment by ulisesbocchio** [comment]
There's a limitation due to the way spring boot resolves properties for `application.yml` or `application.properties`.
There are 2 workarounds:
- encrypt the entire URL: `secret.url=ENC(sdfsdfds...)`
- Move `secret.password` and `secret.url` to a different property files together with:
```java
@EncryptablePropertySource("classpath:encrypted.properties")
```
And you'll be able to make that indirection.
There's a working sample here: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo-simple

**Comment by ajainy** [comment]
Thanks. I will try this.

**Comment by ulisesbocchio** [comment]
as of 1.15 (which I just released) this should work out the box using either `jasypt-spring-boot-starter`, `@EnableEncryptableProperties`, `StandardEncryptableEnvironment` or on custom property sources using `@EncryptablePropertySource`.
Enjoy!
