### ISSUE TITLE
Annotation @RefreshScope does not decrypt

### ISSUE THREAD

**Issue by jmhostalet** [ulisesbocchio/jasypt-spring-boot#62]
I am using @RefreshScope within my class and an attribute 

    @Value("${consulExample}")
    private String consulExample;

I am using Consul as external configuration tool, in Consul I've defined a new key/value with a value encrypted previously with encrypt.sh. A simple GET service returns the value of consulExample.

After booting up the right decrypted value is shown. Now, if I change the value in Consul, after some seconds it is refreshed automatically and consulExample gets the new value, but the new value is NOT decrypted. 

It seems that decrypt is not working for values refreshed dynamically after first initialization.

**Comment by ulisesbocchio** [comment]
Interesting, `jasypt-spring-boot` works intercepting properties at the property source level so as far as the property source stays there and given that the property format is correct it should work. So it might be that Spring is re-creating the property source, and in that case, `jasypt-spring-boot` won't intercept since the interceptors are established with bean factory post processors.
The one thing that should work is `StandardEncryptableEnvironment`. Check out the docs for how to set it up: 
https://github.com/ulisesbocchio/jasypt-spring-boot#custom-environment

**Comment by ulisesbocchio** [comment]
Did the `StandardEncryptableEnvironment` work?

**Comment by jmhostalet** [comment]
I didn't try yet ;-)

**Comment by h-saxena** [comment]
I was having the same issue when using RefreshScope. Changing from boot starter to "StandardEncryptableEnvironment" configuration did solve the problem.

**Comment by ulisesbocchio** [comment]
Thanks for sharing @h-saxena 
I’ll close this issue then!

**Comment by sathish593** [comment]
@ulisesbocchio we are also facing same issue, we tried by adding StandardEncryptableEnvironment, but still jasypt is not decrypting properties on /refresh, it is serving encrypted string. is there any other fix for this?
@h-saxena can you please share your code snippet which may help us. Thank you.
