### ISSUE TITLE
password: ${DB_PASSWORD:ENC@[bxXEba+WWXFUqdxUkobtVw==]} nowt working

### ISSUE THREAD

**Issue by sonersivri** [ulisesbocchio/jasypt-spring-boot#75]
password: ${DB_PASSWORD:ENC(bxXEba+WWXFUqdxUkobtVw==)} property default environment variable not working

**Comment by sonersivri** [comment]
com.ulisesbocchio.jasyptspringboot.detector.DefaultPropertyDetector.isEncrypted(String)

 return (trimmedValue.startsWith(prefix) &&
                trimmedValue.endsWith(suffix));
regex control not startsWith solves problem

**Comment by ulisesbocchio** [comment]
yeah, there is a sort of bug in Spring property resolvers that for some reason, when it looks for properties with default values, it does not resolve the default part of the property through the same mechanism of resolving a property and instead just resolves the default property value.
The workaround you found is valid, otherwise another workaround is depicted in [jasypt-spring-boot-demo-simple](https://github.com/ulisesbocchio/jasypt-spring-boot-samples/blob/master/jasypt-spring-boot-demo-simple/src/main/resources/application.yml) where this would work also:

```yaml
defaultPassword=ENC(bxXEba+WWXFUqdxUkobtVw==)
password=${DB_PASSWORD:${defaultPassword}}
```

**Comment by mwiede** [comment]
the solution has one problem: if you have different master passwords for the `defaultPassword` and the encrypted password passed in as `DB_PASSWORD`, then the decryption will fail, because both values are tried being resolved.
